### ISSUE TITLE
Big jpg collision

### ISSUE THREAD

**Issue by Softminilab** [corkami/collisions#1]
Hello, although you said in the introduction that jpegtran-scans are used on the large image JPG, I still don't know how to use it. I can only change the small image now, but the large image is not available. Please help me, thank you!

**Comment by angea** [comment]
Check https://github.com/corkami/collisions#custom-scans

**Comment by Softminilab** [comment]
I used you `jpg.py` script process my `1.jpg` and `2.jpg`
* 1.jpg size is 272 KB
* 2.jpg size is 103 KB

I change this script below:
```
if max(len(i) for i in c1) >= (273 * 1024)/20 - 8:
#  print "ERROR: The first image file has a segment that is too big!",
#  print "Maybe save it as progressive or reduce its size/scans."
  sys.exit()
```
It's run, but No processing image. please help me, thanks!

**Comment by Softminilab** [comment]
@angea Thanks, I fix it.
