### ISSUE TITLE
SHA-1 collision for mp4 files

### ISSUE THREAD

**Issue by kakumanu-sudhir** [corkami/collisions#4]
Hi,
Was just trying to generate an mp4 file from another mp4 file with same SHA-1 values. Is this possible from this repo? 

I'm trying mp4.py file to do so. Is this the correct file to use? 

What I have also seen is this mp4.py file takes 2 mp4 files as input. Can you please tell why 2 mp4 files are required as input? What is the exact command to generate collided mp4 file with same SHA-1 values?

Thanks a lot for providing this repo.
BR

**Comment by angea** [comment]
This is not possible - please check https://speakerdeck.com/ange/kill-md5 for details.
