### ISSUE TITLE
Finding a binary suitable for collision  for an existing hash

### ISSUE THREAD

**Issue by PvtSec** [corkami/collisions#5]
If I have a hash xfcxfcxfc mapped to string abcde,
Is there a solution for finding another binary/string which matches the hash? Provided, I'm not aware of the string abcde

**Comment by cr-marcstevens** [comment]
What you ask for is called a **preimage** **attack**, targeting a fixed hash value, which are not feasible.
**Collision** **attacks** produce 2 new files that collide and have the same unpredictable random hash value, but these attacks are feasible.
