### ISSUE TITLE
UniColl for "merged" Zip (two texts) creates two zips with same txt file content

### ISSUE THREAD

**Issue by IdanBanani** [corkami/collisions#6]
[](https://github.com/corkami/collisions/blob/master/unicoll.md)
So I've managed to find the [repo ](https://github.com/cr-marcstevens/hashclash) for hashclash (which contains a poc_no.sh which is the script for Unicoll]

I'm trying to understand how was the this example generated with the zip.asm file:
[https://github.com/corkami/collisions/blob/master/examples/collision1.zip](https://github.com/corkami/collisions/blob/master/examples/collision1.zip)
[https://github.com/corkami/collisions/blob/master/examples/collision2.zip](https://github.com/corkami/collisions/blob/master/examples/collision2.zip)

1.Is there a condition/prerequisite on the strings inside the .txt files?

2.When using the zip.asm+ unicoll with N=2 I'm getting two valid zip files with hello.txt that contains "Hello world!" (no "Bye World"). how come?
In the example zip files we get two different zip contents

3. besides (2) . I think it should be mentioned that the CRC32 values should be changed also in .asm file (of the string + new line char).

> Another approach could be to just merge both archives, with their merged layers, and using UniColl - but with **N=2,** which introduces a difference on the 4th byte - to kill the magic signature of the End of Central Directory.

How does UniColl knows to generate from "zip.zip" (nasm output) two different zips with different content? 
[well, it didn't work for me after changing the "Hello world" "Bye world" to my own strings , And I've change N from 1 to 2 in poc_no.sh]

Thank you

---------------
EDIT: It turns out there a lot of "magic" behind the suggested approach.
Unfortunately - the instructions are not so "beginner friendly"

> non generic approach
> 
> Another approach could be to just merge both archives, with their merged layers, and using UniColl - but with N=2, which introduces a difference on the 4th byte - to kill the magic signature of the End of Central Directory.
> 
> This means one could collide two arbitrary ZIP with a single UniColl and 24 bytes of set prefix.
> 
> A typical End of Central Directory, which is 22 bytes if the comment is empty:
> 
> 00: 504b 0506 0000 0000 0000 0000 0000 0000  PK..............
> 10: 0000 0000 0000                           ......
> If we use this as prefix (pad the prefix to 16 bits) for UniColl and N=2, the difference is on the 4th byte, killing the magic .P .K 05 06 by changing it predictably to .P .K 05 86

**Comment by angea** [comment]
1. The Strings have no pre-requisite.
2. Maybe use a different parser.
3. indeed, the CRC need to be updated.
4. get the prefix from the generated zip, then compute Unicoll.

Yes, it's not a magic 'one step' solution, but it's clumsy and has a bad compatibility anyway.
