### ISSUE TITLE
Strategy: hash the output of a quine

### ISSUE THREAD

**Issue by jimukgb** [corkami/collisions#9]
A Quine is a program that prints its own source code. Therefore, a quine can be modified to print the hash of its source code, rather than the source code itself and as such it will also be a hashquine. That should be added under the Self-Check paragraph. Similar to Self-Check, it doesn't require any cryptographic attack on the underlying hash function itself. It also requires the file format to be an executable.

**Comment by angea** [comment]
Yes. Self-check can be binary executables too.
